---
ociLogId: "ocid1.log.oc1.ap-singapore-1.amaaaaaa2yseieqadcrmdmhrqynd4o47thhwhsapqhscjk7d2z2n26iffzja"
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
